### ISSUE TITLE
Create plots with the observability of objects

### ISSUE THREAD

**Issue by j-faria** [DanielAndreasen/ObservationTools#2]
Basically, whatever [STARALT](http://catserver.ing.iac.es/staralt/) can do. But we can (and should) divide this into specific requests

- [ ] altitude of object against time for a specific night
- [ ] ...

**Comment by j-faria** [comment]
I don't know how to add labels :(

**Comment by DanielAndreasen** [comment]
You can add labels in the settings to the right, but maybe this is only for the owner. Do you want more rights? :)

**Comment by DanielAndreasen** [comment]
We could probably use some stuff from [here](http://www.hs.uni-hamburg.de/DE/Ins/Per/Czesla/PyA/PyA_0_7_0/pyaslDoc/aslDoc/transitVisibility.html)

**Comment by j-faria** [comment]
Wow cool plot! I will try to write something starting from there

**Comment by DanielAndreasen** [comment]
This is done with pull request #3 merged. Great job!
